config/routes.rb
Desk::Application.routes.draw do
  root 'home#index'

  get "/auth/:provider/callback" => "sessions#create"
  get "/logout" => "sessions#destroy", :as => :logout
  get "/login"  => "sessions#login", :as => :login

  resources :case, only: [:index,:show]
  resources :label, only: [:index,:show, :create]
  resources :filter, only: [:index,:show]
end

app/models/desk_wrapper.rb
module DeskWrapper
  class Client
    attr_accessor :client, :options

    def initialize(opts)
      @options = defaults.merge(opts)
      @client = build_client
    end

    def cases
      get('cases')
    end

    def labels
      get('labels')
    end

    def new_label(opts)
      response = post('labels',opts)
    end

    def filters
      get('filters')
    end

    def filter_cases(id)
      get("filters/#{id}/cases")
    end

    def post(path, options)
      response = client.post(path, options)
    end

    def get(endpoint)
      response = client.get(endpoint)
      entries = response.body['_embedded']['entries']
      entries.sort_by{|x| x['position'] }
    end

    def defaults
      {
        consumer_key: API_KEY,
        consumer_secret: API_SECRET,
      }
    end

    def build_client
      Faraday.new URI.join(API_SITE,'api/v2').to_s do |conn|
        conn.request :oauth, options
        conn.request :json

        conn.response :json, :content_type => /\bjson$/

        conn.use :instrumentation
        conn.use :http_cache, store: :memory_store

        conn.adapter Faraday.default_adapter
      end
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  def self.create_with_omniauth(auth)
    create! do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.name = auth.info.name
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :require_login
  protect_from_forgery with: :exception

  helper_method :current_user
  helper_method :desk

  def current_user
    @current_user ||= (
      begin
        User.find(session[:user_id]) if session[:user_id]
      rescue ActiveRecord::RecordNotFound
        nil
      end
    )
  end

  def desk
    opts = {token: session[:oauth_token], token_secret: session[:oauth_secret]}
    @desk ||= DeskWrapper::Client.new(opts)
  end

  def require_login
    if current_user.nil?
      redirect_to login_url
    end
  end
end

app/controllers/case_controller.rb
class CaseController < ApplicationController
end

app/controllers/filter_controller.rb
class FilterController < ApplicationController
  def show
    @user = current_user
    @filters = desk.filters
    @labels = desk.labels

    @cases = @desk.filter_cases(params['id'])

    render 'home/index'
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @user = current_user
    @cases = desk.cases
    @filters = desk.filters
    @labels = desk.labels
  end
end

app/controllers/label_controller.rb
class LabelController < ApplicationController
  def create
    wanted_keys = %w(name description types color)
    opts = params.select{|k,v| wanted_keys.include?(k)}

    desk.new_label(opts)

    @user = current_user
    @filters = desk.filters
    @labels = desk.labels
    @cases = @desk.cases
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :require_login, only: [:create, :login]

  def create
    auth = request.env["omniauth.auth"]
    user = User.find_by_provider_and_uid(auth["provider"], auth["uid"]) || User.create_with_omniauth(auth)
    session[:user_id] = user.id
    session[:oauth_token] = auth.credentials.token
    session[:oauth_secret] = auth.credentials.secret
    redirect_to root_url, :notice => "Signed in!"
  end

  def destroy
    [:user_id, :oauth_token, :oauth_secret].each do |sym|
      session[sym] = nil
    end
    redirect_to root_url, :notice => "Signed out!"
  end

  def login
    render layout: 'bare'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/case_helper.rb
module CaseHelper
end

app/helpers/filter_helper.rb
module FilterHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/label_helper.rb
module LabelHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/case/_list.html.haml
%table
  %thead
    %tr
      %th Subject
      %th Labels
    %tbody
      = render partial: 'case/row', collection: cases, as: 'c'

app/views/case/_row.html.haml
/
  = c.to_yaml
%tr
  %td= c['subject']
  %td= render partial: "label/button", collection: c['labels'], as: 'label_text'

app/views/filter/_list.html.haml
- filter_id = filter['_links']['cases']['href'].split('/')[-2].to_i
%li
  = link_to(filter['name'], filter_path(filter_id))

app/views/home/_cases.html.haml
%table
  %thead
    %tr
      %th Subject
      %th Labels
    %tbody
      = render partial: 'case_row', collection: cases, as: 'c'

app/views/home/_labels.html.haml
%span.label.round.radius= label_text

app/views/home/index.html.haml
.row
  .small-2.columns
    %h2 Filters
    %ul.side-nav
      = render partial: 'filter/list', collection: @filters, as: :filter
  .small-7.columns
    %h2 Cases
    - if @cases.empty?
      No cases found!
    - else
      = render partial: 'case/list', locals: {cases: @cases}
  .small-3.columns
    %h2 Labels
    %ul.side-nav
      = render partial: 'label/list', collection: @labels, as: :label_nav
      = render partial: 'label/form'

app/views/label/_button.html.haml
%span.label.round.radius= label_text

app/views/label/_form.html.haml
= form_tag({controller: :label, action: :create}, method: 'post', :data => {'abide' => true}) do
  %fieldset
    %legend New Label
    .name-field
      = label_tag :name, 'Name'
      = text_field_tag(:name, '', {:required => true})
    .description-field
      = label_tag :description, 'Description'
      = text_area_tag(:description, '', {:required => true})
    .type-field
      = label_tag 'Types'
      %ul{style: 'list-style-type: none'}
        :ruby
          checkboxes = {
            case: 'Case',
            macro: 'Macro',
            article: 'Article'
          }
        - checkboxes.each do |name,val|
          %li
            %input{type: :checkbox, name: 'types[]', value: name}
            = label_tag name, val
    .color-field
      = label_tag :color, 'Color'
      - colors = %w(default blue white yellow red orange green black purple brown grey pink)
      = select_tag 'color', options_for_select(colors)
    = submit_tag('New', class: [:button, :postfix])

app/views/label/_list.html.haml
%li
  = render partial: 'label/button', locals: {label_text: label_nav['name']}

app/views/layouts/_head.html.haml
- content_for :head do
  %meta{:charset => "utf-8"}/
  %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}/
  %title= content_for?(:title) ? yield(:title) : "foundation-rails"
  = stylesheet_link_tag    "application"
  = javascript_include_tag "vendor/modernizr"
  = csrf_meta_tags

app/views/layouts/_javascripts.html.haml
= javascript_include_tag "application"

app/views/layouts/_nav.html.haml
%nav.top-bar
  %ul.title-area
    %li.name
      %h1= link_to("Welcome, #{current_user.name}", root_path)

  %section.top-bar-section
    %ul.right
      %li.active
        = link_to "Sign Out", logout_path

app/views/layouts/application.html.haml
!!!
%html{:lang => "en"}
  %head
    %meta{:charset => "utf-8"}/
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}/
    %title= content_for?(:title) ? yield(:title) : "You Should Hire Fotios!"
    = stylesheet_link_tag    "application"
    = javascript_include_tag "vendor/modernizr"
    = csrf_meta_tags
  %body
    = render partial: 'layouts/nav'
    = yield
    = javascript_include_tag "application"

app/views/layouts/bare.html.haml
!!!
%html{:lang => "en"}
  %head
    %meta{:charset => "utf-8"}/
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}/
    %title= content_for?(:title) ? yield(:title) : "You Should Hire Fotios!"
    = stylesheet_link_tag    "application"
    = javascript_include_tag "vendor/modernizr"
    = csrf_meta_tags
  %body
    = yield
    = javascript_include_tag "application"